/**
 * Central place for all user-facing strings (Dutch).
 * Keep code/comments in English; keep UI copy here.
 */
export const copy = {
  app: {
    name: "BibSync",
    tagline: "Synchroniseer je studiepauzes met je groep.",
    description:
      "BibSync helpt studenten die samen in de bib zitten om pauzes te plannen, te stemmen en te zien wie er aanwezig is.",
  },
  nav: {
    login: "Inloggen",
    register: "Registreren",
    logout: "Uitloggen",
    profile: "Profiel",
    toApp: "Naar de app",
    admin: "Admin",
  },
  admin: {
    title: "Admin",
    subtitle: "Beheer alle rooms in BibSync.",
    badge: "Admin",
    owner: "Eigenaar",
    manage: "Beheren",
    empty: "Er zijn nog geen rooms.",
  },
  landing: {
    heroTitle: "Studeer samen, pauzeer samen.",
    heroSubtitle:
      "Plan pauzes, stem op voorstellen en zie in één oogopslag wie er aan het studeren is.",
    ctaPrimary: "Account aanmaken",
    ctaSecondary: "Ik heb al een account",
  },
  auth: {
    loginTitle: "Welkom terug",
    loginSubtitle: "Log in om verder te gaan.",
    registerTitle: "Account aanmaken",
    registerSubtitle: "Maak een account om met je groep te starten.",
    tabPassword: "Wachtwoord",
    tabMagicLink: "Magic link",
    emailLabel: "E-mailadres",
    emailPlaceholder: "jij@voorbeeld.be",
    passwordLabel: "Wachtwoord",
    passwordPlaceholder: "••••••••",
    displayNameLabel: "Weergavenaam",
    displayNamePlaceholder: "Hoe je groep je kent",
    submitLogin: "Inloggen",
    submitRegister: "Registreren",
    submitMagicLink: "Stuur magic link",
    submittingLogin: "Bezig met inloggen…",
    submittingRegister: "Account aanmaken…",
    submittingMagicLink: "Versturen…",
    noAccount: "Nog geen account?",
    haveAccount: "Heb je al een account?",
    registerLink: "Registreer hier",
    loginLink: "Log hier in",
    magicLinkHint:
      "We sturen je een link om in te loggen zonder wachtwoord.",
    magicLinkSent:
      "Check je mailbox — we stuurden je een inloglink.",
    confirmEmailSent:
      "Bijna klaar! Check je mailbox om je account te bevestigen.",
    invalidCredentials: "E-mailadres of wachtwoord klopt niet.",
    emailInUse: "Dit e-mailadres is al in gebruik. Log in plaats daarvan in.",
    rateLimited:
      "Te veel pogingen in korte tijd. Wacht even en probeer opnieuw.",
    weakPassword: "Kies een sterker wachtwoord (minstens 8 tekens).",
    emailNotConfirmed:
      "Bevestig eerst je e-mailadres — check je mailbox voor de link.",
    genericError: "Er ging iets mis. Probeer het opnieuw.",
    confirmFailed: "De bevestigingslink is ongeldig of verlopen.",
  },
  profile: {
    title: "Profiel",
    emailLabel: "E-mailadres",
    displayNameLabel: "Weergavenaam",
    memberSince: "Lid sinds",
    avatar: {
      upload: "Foto uploaden",
      remove: "Verwijderen",
      updated: "Profielfoto bijgewerkt.",
      removed: "Profielfoto verwijderd.",
      invalid: "Kies een afbeelding.",
      tooLarge: "Afbeelding mag max 5 MB zijn.",
      error: "Uploaden mislukt. Probeer opnieuw.",
    },
  },
  appHome: {
    welcome: (name: string) => `Welkom ${name}`,
    placeholder: "Hier komen straks je rooms.",
  },
  validation: {
    emailInvalid: "Geef een geldig e-mailadres in.",
    passwordTooShort: "Wachtwoord moet minstens 8 tekens zijn.",
    displayNameRequired: "Geef een weergavenaam in.",
    displayNameTooLong: "Weergavenaam mag max 40 tekens zijn.",
  },
  notFound: {
    title: "Pagina niet gevonden",
    body: "Deze pagina bestaat niet (meer) of je hebt er geen toegang toe.",
    cta: "Naar de app",
  },
  common: {
    cancel: "Annuleren",
    save: "Opslaan",
    saving: "Opslaan…",
    delete: "Verwijderen",
    confirm: "Bevestigen",
    back: "Terug",
    loading: "Laden…",
    genericError: "Er ging iets mis. Probeer het opnieuw.",
    notAuthenticated: "Je bent niet (meer) ingelogd.",
  },
  rooms: {
    listTitle: "Mijn rooms",
    listSubtitle: "Rooms waar je lid van bent.",
    newRoom: "Nieuwe room",
    joinRoom: "Join via code",
    empty: "Je zit nog in geen enkele room. Maak er een aan of join via een code.",
    membersCount: (n: number) => `${n} ${n === 1 ? "lid" : "leden"}`,
    owner: "Eigenaar",
    you: "jij",
    switcherAll: "Alle rooms",
    open: "Openen",
    new: {
      title: "Nieuwe room",
      subtitle: "Geef je room een naam. De join code maken we automatisch.",
      nameLabel: "Naam",
      namePlaceholder: "bv. Examens januari",
      descriptionLabel: "Beschrijving (optioneel)",
      descriptionPlaceholder: "Waar studeren jullie samen?",
      submit: "Room aanmaken",
      submitting: "Aanmaken…",
    },
    join: {
      title: "Join een room",
      subtitle: "Vul de 6-cijferige code in die je van je groep kreeg.",
      codeLabel: "Join code",
      codePlaceholder: "K7P2QM",
      submit: "Joinen",
      submitting: "Joinen…",
      notFound: "Geen room gevonden met die code.",
    },
    joinCode: "Join code",
    copyCode: "Code kopiëren",
    codeCopied: "Code gekopieerd",
    created: "Room aangemaakt.",
    joined: "Je bent toegevoegd aan de room.",
    left: "Je hebt de room verlaten.",
    leave: "Room verlaten",
    leaveConfirmTitle: "Room verlaten?",
    leaveConfirmBody:
      "Je kan later opnieuw joinen met de join code.",
    ownerCannotLeave:
      "Als eigenaar kan je de room niet verlaten. Verwijder ze in plaats daarvan.",
    onlyOwner: "Alleen de eigenaar van de room kan dit doen.",
    settings: {
      title: "Room-instellingen",
      rename: "Naam & beschrijving",
      renamed: "Room bijgewerkt.",
      regenerate: "Join code vernieuwen",
      regenerateHint:
        "De oude code werkt daarna niet meer.",
      regenerated: "Nieuwe join code aangemaakt.",
      members: "Leden",
      kick: "Verwijderen uit room",
      kicked: "Lid verwijderd.",
      dangerZone: "Gevaarlijke zone",
      deleteRoom: "Room verwijderen",
      deleteConfirmTitle: "Room verwijderen?",
      deleteConfirmBody:
        "Dit verwijdert de room met alle pauzes, stemmen en berichten. Dit kan niet ongedaan gemaakt worden.",
      deleted: "Room verwijderd.",
    },
    validation: {
      nameRequired: "Geef de room een naam.",
      nameTooLong: "Naam mag max 60 tekens zijn.",
      descriptionTooLong: "Beschrijving mag max 280 tekens zijn.",
      joinCodeLength: "Een join code bestaat uit 6 tekens.",
    },
    tabs: {
      breaks: "Pauzes",
      presence: "Wie is er?",
      chat: "Chat",
    },
    chatPlaceholder: "Chat komt binnenkort beschikbaar.",
  },
  instantBreak: {
    button: "Pauze nu",
    pushed: "Jij wil pauze ✓",
    durationLabel: "Duur",
    hint: (needed: number, seconds: number) =>
      `${needed} mensen die binnen ${seconds}s drukken = meteen pauze, wat er ook gepland staat.`,
    waiting: (count: number, needed: number) =>
      `${count}/${needed} — druk ook om pauze af te dwingen!`,
    wantsBreak: (names: string) => `${names} wil pauze`,
    active: "Het is pauze! 🎉",
    activeBody: "Genoeg mensen wilden pauze — leg je boeken even neer.",
    until: (time: string) => `tot ${time}`,
    remaining: (min: number) => `nog ${min} min`,
    triggeredBy: (name: string) => `afgedwongen door ${name}`,
    failed: "Kon je pauze-stem niet doorgeven. Probeer opnieuw.",
  },
  proposals: {
    title: "Pauzevoorstellen",
    new: "Nieuw voorstel",
    empty: "Nog geen pauzevoorstellen. Doe een voorstel 👇",
    slots: {
      title: "Vaste momenten",
      free: "Vrije voorstellen",
      average: "Gemiddeld",
      defaultLabel: "standaard",
      yourPref: "Jouw voorkeur",
      save: "Opslaan",
      clear: "Wissen",
      saved: "Voorkeur opgeslagen.",
      empty: "Nog geen voorkeuren — geef de jouwe of stem op de standaard.",
      earlier: "Eerdere momenten",
    },
    form: {
      title: "Pauze voorstellen",
      typeLabel: "Type",
      dateLabel: "Datum",
      timeLabel: "Starttijd",
      hour: "Uur",
      minute: "Minuten",
      durationLabel: "Duur",
      noteLabel: "Notitie (optioneel)",
      notePlaceholder: "bv. afspraak aan de hoofdingang",
      submit: "Voorstel plaatsen",
      submitting: "Plaatsen…",
    },
    types: {
      lunch: "Lunch",
      dinner: "Avondeten",
      coffee: "Pauze",
      other: "Andere",
    },
    duration: (min: number) =>
      min >= 60
        ? `${min / 60} u${min % 60 ? ` ${min % 60} min` : ""}`
        : `${min} min`,
    today: "Vandaag",
    tomorrow: "Morgen",
    winner: "Beslist",
    created: "Voorstel geplaatst.",
    deleted: "Voorstel verwijderd.",
    deleteConfirm: "Dit voorstel verwijderen?",
    by: "door",
    calendar: {
      day: "Dag",
      week: "Week",
      month: "Maand",
      today: "Vandaag",
      prev: "Vorige",
      next: "Volgende",
      emptyRange: "Geen voorstellen in deze periode.",
    },
    comments: {
      title: "Reacties",
      placeholder: "Schrijf een reactie…",
      send: "Plaats",
      empty: "Nog geen reacties.",
      toggle: (n: number) =>
        n === 0
          ? "Reageren"
          : `${n} ${n === 1 ? "reactie" : "reacties"}`,
      error: "Reactie niet geplaatst. Probeer opnieuw.",
    },
    votes: {
      yes: "Ja",
      maybe: "Misschien",
      no: "Nee",
      noVotes: "Nog geen stemmen",
      error: "Stem niet opgeslagen. Probeer opnieuw.",
    },
    validation: {
      dateInPast: "Kies vandaag of een datum in de toekomst.",
      dateTooFar: "Kies een datum binnen 7 dagen.",
      timeQuarter: "Starttijd moet op het kwartier vallen.",
      durationInvalid: "Kies een geldige duur.",
      noteTooLong: "Notitie mag max 200 tekens zijn.",
      slotTaken:
        "Er staat al een voorstel op dit tijdstip. Kies een ander moment.",
    },
  },
  presence: {
    title: "Wie is er?",
    empty: "Nog niemand actief.",
    yourStatus: "Jouw status",
    backAt: "Terug om",
    backAtLabel: "Terug om (optioneel)",
    lastSeen: (time: string) => `laatst gezien om ${time}`,
    updated: "Status bijgewerkt.",
    statuses: {
      studying: "Aan het studeren",
      break: "Pauze",
      lunch: "Lunch",
      away: "Weg",
      done: "Klaar voor vandaag",
    },
  },
  chat: {
    title: "Chat",
    empty: "Nog geen berichten — zeg hallo 👋",
    placeholder: "Schrijf een bericht…",
    send: "Versturen",
    sending: "Verzendt…",
    loadMore: "Laad oudere berichten",
    newMessages: (n: number) =>
      `${n} ${n === 1 ? "nieuw bericht" : "nieuwe berichten"} ↓`,
    error: "Bericht niet verzonden. Probeer opnieuw.",
    rainbowOn: "🌈 Full rainbow mode aan!",
    rainbowOff: "Rainbow mode uit.",
    react: "Reageer",
    gif: {
      button: "GIF kiezen",
      title: "Kies een GIF",
      search: "Zoek een GIF…",
      empty: "Geen GIFs gevonden.",
      poweredBy: "Powered by GIPHY",
    },
  },
  food: {
    title: "Wat eten we?",
    nav: "Eten",
    subtitle: "Stem per dag op waar we gaan eten.",
    new: "Nieuw eetvoorstel",
    empty: "Nog geen eetvoorstellen. Doe een voorstel 👇",
    created: "Eetvoorstel geplaatst.",
    deleted: "Eetvoorstel verwijderd.",
    presets: ["Brug", "Panda", "Okay"],
    custom: "Andere…",
    slots: {
      title: "Vaste maaltijden",
      free: "Vrije eetvoorstellen",
      defaultLabel: "standaard",
      yourChoice: "Jouw keuze",
      save: "Opslaan",
      clear: "Wissen",
      saved: "Keuze opgeslagen.",
      empty: "Nog geen keuzes — geef de jouwe of stem op de standaard.",
      earlier: "Eerdere maaltijden",
    },
    form: {
      title: "Waar gaan we eten?",
      choiceLabel: "Keuze",
      customLabel: "Andere (zelf invullen)",
      customPlaceholder: "bv. frituur",
      dateLabel: "Datum",
      timeLabel: "Hoe laat",
      noteLabel: "Notitie (optioneel)",
      notePlaceholder: "bv. vertrek om 12u",
      submit: "Voorstel plaatsen",
      submitting: "Plaatsen…",
    },
    validation: {
      choiceRequired: "Kies of typ waar je wil eten.",
      choiceTooLong: "Max 60 tekens.",
    },
    slotTaken: "Deze keuze staat al voor die dag.",
  },
  pwa: {
    title: "Installeer als app",
    subtitle:
      "Voeg BibSync toe aan je beginscherm voor snelle, full-screen toegang.",
    install: "Installeren",
    iosHint:
      'Tik op het Deel-icoon (vierkant met pijl) en kies "Zet op beginscherm".',
    genericHint:
      'Open deze site op je telefoon in Chrome of Safari en kies "Toevoegen aan beginscherm".',
  },
  push: {
    title: "Meldingen",
    subtitle: "Krijg een melding op dit toestel bij nieuwe voorstellen.",
    enable: "Meldingen aanzetten",
    disable: "Meldingen uitzetten op dit toestel",
    enabledToast: "Meldingen aangezet 🔔",
    disabledToast: "Meldingen uitgezet.",
    denied:
      "Meldingen zijn geblokkeerd. Zet ze aan in je browser-/systeeminstellingen.",
    unsupported:
      "Meldingen worden hier niet ondersteund. Op iPhone: installeer eerst de app (Zet op beginscherm).",
    error: "Kon meldingen niet instellen. Probeer opnieuw.",
    prefProposals: "Nieuwe pauzevoorstellen",
    prefFood: "Nieuwe eetvoorstellen",
    prefChat: "Nieuwe chatberichten",
    prefComments: "Reacties op mijn voorstellen",
    prefVotes: "Stemmen op mijn voorstellen",
    newProposal: "Nieuw pauzevoorstel",
    newFood: "Nieuw eetvoorstel",
    newMessage: "Nieuw bericht",
    newComment: "Nieuwe reactie op je voorstel",
    newVote: "Nieuwe stem op je voorstel",
    gifMessage: "📷 GIF",
  },
} as const;
