/**
 * Central place for all user-facing strings (Dutch).
 * Keep code/comments in English; keep UI copy here.
 */
export const copy = {
  app: {
    name: "BibSync",
    tagline: "Synchroniseer je studiepauzes met je groep.",
    description:
      "BibSync helpt studenten die samen in de bib zitten om pauzes te plannen, te stemmen en te zien wie er aanwezig is.",
  },
  nav: {
    login: "Inloggen",
    register: "Registreren",
    logout: "Uitloggen",
    profile: "Profiel",
    toApp: "Naar de app",
    admin: "Admin",
  },
  admin: {
    title: "Admin",
    subtitle: "Beheer alle rooms in BibSync.",
    badge: "Admin",
    owner: "Eigenaar",
    manage: "Beheren",
    empty: "Er zijn nog geen rooms.",
  },
  landing: {
    heroTitle: "Studeer samen, pauzeer samen.",
    heroSubtitle:
      "Plan pauzes, stem op voorstellen en zie in één oogopslag wie er aan het studeren is.",
    ctaPrimary: "Account aanmaken",
    ctaSecondary: "Ik heb al een account",
  },
  auth: {
    loginTitle: "Welkom terug",
    loginSubtitle: "Log in om verder te gaan.",
    registerTitle: "Account aanmaken",
    registerSubtitle: "Maak een account om met je groep te starten.",
    tabPassword: "Wachtwoord",
    tabMagicLink: "Magic link",
    emailLabel: "E-mailadres",
    emailPlaceholder: "jij@voorbeeld.be",
    passwordLabel: "Wachtwoord",
    passwordPlaceholder: "••••••••",
    displayNameLabel: "Weergavenaam",
    displayNamePlaceholder: "Hoe je groep je kent",
    submitLogin: "Inloggen",
    submitRegister: "Registreren",
    submitMagicLink: "Stuur magic link",
    submittingLogin: "Bezig met inloggen…",
    submittingRegister: "Account aanmaken…",
    submittingMagicLink: "Versturen…",
    noAccount: "Nog geen account?",
    haveAccount: "Heb je al een account?",
    registerLink: "Registreer hier",
    loginLink: "Log hier in",
    magicLinkHint:
      "We sturen je een link om in te loggen zonder wachtwoord.",
    magicLinkSent:
      "Check je mailbox — we stuurden je een inloglink.",
    confirmEmailSent:
      "Bijna klaar! Check je mailbox om je account te bevestigen.",
    invalidCredentials: "E-mailadres of wachtwoord klopt niet.",
    emailInUse: "Dit e-mailadres is al in gebruik. Log in plaats daarvan in.",
    rateLimited:
      "Te veel pogingen in korte tijd. Wacht even en probeer opnieuw.",
    weakPassword: "Kies een sterker wachtwoord (minstens 8 tekens).",
    emailNotConfirmed:
      "Bevestig eerst je e-mailadres — check je mailbox voor de link.",
    genericError: "Er ging iets mis. Probeer het opnieuw.",
    confirmFailed: "De bevestigingslink is ongeldig of verlopen.",
  },
  profile: {
    title: "Profiel",
    emailLabel: "E-mailadres",
    displayNameLabel: "Weergavenaam",
    memberSince: "Lid sinds",
    nameEdit: {
      save: "Opslaan",
      cost: (n: number) => `Kost ${n} bibcoins · max 1× per dag`,
      updated: "Weergavenaam bijgewerkt.",
      unchanged: "Dat is al je weergavenaam.",
      alreadyToday: "Je kan je weergavenaam maar 1× per dag wijzigen.",
      insufficient: (n: number) =>
        `Je hebt niet genoeg bibcoins (${n} nodig).`,
      error: "Wijzigen mislukt. Probeer opnieuw.",
    },
    public: {
      coins: "Bibcoins",
      proposals: "Voorstellen",
      comments: "Reacties",
      messages: "Chatberichten",
      cosmeticsTitle: "Gekocht in de shop",
      noCosmetics: "Nog niets gekocht in de shop.",
      notFound: "Deze gebruiker bestaat niet.",
    },
    avatar: {
      upload: "Foto uploaden",
      remove: "Verwijderen",
      updated: "Profielfoto bijgewerkt.",
      removed: "Profielfoto verwijderd.",
      invalid: "Kies een afbeelding.",
      tooLarge: "Afbeelding mag max 5 MB zijn.",
      error: "Uploaden mislukt. Probeer opnieuw.",
    },
  },
  appHome: {
    welcome: (name: string) => `Welkom ${name}`,
    placeholder: "Hier komen straks je rooms.",
  },
  validation: {
    emailInvalid: "Geef een geldig e-mailadres in.",
    passwordTooShort: "Wachtwoord moet minstens 8 tekens zijn.",
    displayNameRequired: "Geef een weergavenaam in.",
    displayNameTooLong: "Weergavenaam mag max 40 tekens zijn.",
  },
  notFound: {
    title: "Pagina niet gevonden",
    body: "Deze pagina bestaat niet (meer) of je hebt er geen toegang toe.",
    cta: "Naar de app",
  },
  common: {
    cancel: "Annuleren",
    save: "Opslaan",
    saving: "Opslaan…",
    delete: "Verwijderen",
    confirm: "Bevestigen",
    back: "Terug",
    loading: "Laden…",
    genericError: "Er ging iets mis. Probeer het opnieuw.",
    notAuthenticated: "Je bent niet (meer) ingelogd.",
  },
  rooms: {
    listTitle: "Mijn rooms",
    listSubtitle: "Rooms waar je lid van bent.",
    newRoom: "Nieuwe room",
    joinRoom: "Join via code",
    empty: "Je zit nog in geen enkele room. Maak er een aan of join via een code.",
    membersCount: (n: number) => `${n} ${n === 1 ? "lid" : "leden"}`,
    owner: "Eigenaar",
    you: "jij",
    switcherAll: "Alle rooms",
    open: "Openen",
    new: {
      title: "Nieuwe room",
      subtitle: "Geef je room een naam. Laat de code leeg voor een willekeurige, of kies je eigen.",
      nameLabel: "Naam",
      namePlaceholder: "bv. Examens januari",
      descriptionLabel: "Beschrijving (optioneel)",
      descriptionPlaceholder: "Waar studeren jullie samen?",
      codeLabel: "Eigen code (optioneel)",
      codePlaceholder: "bv. THERMI",
      codeHint: "4–12 letters/cijfers. Leeg = willekeurige code.",
      codeAvailable: "✓ beschikbaar",
      codeTaken: "✗ al in gebruik",
      codeChecking: "controleren…",
      submit: "Room aanmaken",
      submitting: "Aanmaken…",
    },
    join: {
      title: "Join een room",
      subtitle: "Vul de code in die je van je groep kreeg.",
      codeLabel: "Join code",
      codePlaceholder: "K7P2QM",
      submit: "Joinen",
      submitting: "Joinen…",
      notFound: "Geen room gevonden met die code.",
    },
    joinCode: "Join code",
    copyCode: "Code kopiëren",
    codeCopied: "Code gekopieerd",
    created: "Room aangemaakt.",
    joined: "Je bent toegevoegd aan de room.",
    left: "Je hebt de room verlaten.",
    leave: "Room verlaten",
    leaveConfirmTitle: "Room verlaten?",
    leaveConfirmBody:
      "Je kan later opnieuw joinen met de join code.",
    ownerCannotLeave:
      "Als eigenaar kan je de room niet verlaten. Verwijder ze in plaats daarvan.",
    onlyOwner: "Alleen de eigenaar van de room kan dit doen.",
    settings: {
      title: "Room-instellingen",
      rename: "Naam & beschrijving",
      renamed: "Room bijgewerkt.",
      regenerate: "Join code vernieuwen",
      regenerateHint:
        "De oude code werkt daarna niet meer.",
      regenerated: "Nieuwe join code aangemaakt.",
      customCode: "Eigen code instellen",
      customCodeHint:
        "Kies een makkelijk te onthouden code (4–12 letters/cijfers).",
      customCodePlaceholder: "bv. THERMI",
      setCode: "Instellen",
      codeSet: "Code ingesteld.",
      members: "Leden",
      kick: "Verwijderen uit room",
      kicked: "Lid verwijderd.",
      location: "Locatie (aanwezigheid)",
      locationHint:
        "Klik op de kaart om de plek van de room te zetten. Leden worden 'ter plaatse' getoond als ze binnen de straal zitten.",
      locationRadius: "Straal",
      locationUseTherminal: "Gebruik De Therminal (Gent)",
      locationSave: "Locatie opslaan",
      locationSaved: "Locatie opgeslagen.",
      locationClear: "Locatie wissen",
      locationCleared: "Locatie gewist.",
      locationNone: "Nog geen locatie ingesteld.",
      locationPick: "Klik op de kaart om een plek te kiezen.",
      dangerZone: "Gevaarlijke zone",
      deleteRoom: "Room verwijderen",
      deleteConfirmTitle: "Room verwijderen?",
      deleteConfirmBody:
        "Dit verwijdert de room met alle pauzes, stemmen en berichten. Dit kan niet ongedaan gemaakt worden.",
      deleted: "Room verwijderd.",
    },
    validation: {
      nameRequired: "Geef de room een naam.",
      nameTooLong: "Naam mag max 60 tekens zijn.",
      descriptionTooLong: "Beschrijving mag max 280 tekens zijn.",
      joinCodeLength: "Een join code is 4–12 tekens.",
      codeLength: "Code is 4–12 tekens.",
      codeChars: "Code mag enkel letters en cijfers bevatten.",
      codeTaken: "Die code is al in gebruik. Kies een andere.",
    },
    tabs: {
      overview: "Overzicht",
      chat: "Chat",
      games: "Games",
      markt: "Markt",
      steps: "Stappen",
    },
    navLabel: "Sectie-navigatie",
  },
  instantBreak: {
    button: "Pauze nu",
    pushed: "Jij wil pauze ✓",
    durationLabel: "Duur",
    hint: (needed: number, seconds: number) =>
      `${needed} mensen die binnen ${seconds}s drukken = meteen pauze, wat er ook gepland staat.`,
    waiting: (count: number, needed: number) =>
      `${count}/${needed} — druk ook om pauze af te dwingen!`,
    wantsBreak: (names: string) => `${names} wil pauze`,
    active: "Het is pauze! 🎉",
    activeBody: "Genoeg mensen wilden pauze — leg je boeken even neer.",
    until: (time: string) => `tot ${time}`,
    remaining: (min: number) => `nog ${min} min`,
    triggeredBy: (name: string) => `afgedwongen door ${name}`,
    failed: "Kon je pauze-stem niet doorgeven. Probeer opnieuw.",
  },
  timeout: {
    banner: "🚨 Je zit in timeout — bied je excuses aan!",
    bannerSub: "Gedraag je. Een beheerder heft je timeout weer op.",
    set: (name: string) => `${name} zit nu in timeout 😤`,
    cleared: (name: string) => `${name} mag weer meedoen.`,
    unknownUser: "Geen lid met die naam — kies uit de lijst.",
  },
  poker: {
    nav: "Poker",
    title: "Poker",
    subtitle:
      "Texas Hold'em met je studiegroep — speel met fiches, niet met geld.",
    unavailable: "Poker is even niet beschikbaar. Probeer het later opnieuw.",
    busy: "Iemand was je net voor. Probeer opnieuw.",
    handInProgress: "Er loopt al een hand.",
    noHand: "Er is geen lopende hand.",
    sit: "Neem plaats",
    seated: "Je zit aan tafel",
    deal: "Deel hand",
    rebuy: "Bijkopen",
    leave: "Tafel verlaten",
    leaveMidHand: "Je zit in een hand — verlaten betekent folden.",
    fold: "Fold",
    check: "Check",
    call: "Call",
    callAmount: (n: number) => `Call ${n}`,
    raise: "Verhoog",
    raiseTo: (n: number) => `Naar ${n}`,
    allin: "All-in",
    amountLabel: "Bedrag",
    pot: (n: number) => `Pot ${n}`,
    chips: (n: number) => `${n} bibcoins`,
    toCall: (n: number) => `${n} te callen`,
    noCoins: "Je hebt geen bibcoins om in te zetten — verdien er eerst wat.",
    buyInNote: "Je hele saldo gaat als inzet de tafel op.",
    yourTurn: "Jouw beurt",
    waitingFor: (name: string) => `Wachten op ${name}…`,
    dealer: "D",
    smallBlindTag: "SB",
    bigBlindTag: "BB",
    blinds: (sb: number, bb: number) => `Blinds ${sb}/${bb}`,
    street: {
      preflop: "Preflop",
      flop: "Flop",
      turn: "Turn",
      river: "River",
    },
    foldedTag: "fold",
    allInTag: "all-in",
    outTag: "leeg",
    showdown: "Showdown",
    wins: (name: string, amount: number) => `${name} wint ${amount}`,
    splitNote: "Pot verdeeld",
    yourCards: "Jouw kaarten",
    community: "Tafelkaarten",
    handNo: (n: number) => `Hand #${n}`,
    busted: "Je bibcoins op deze tafel zijn op. Verlaat de tafel en verdien bij.",
    empty: "Nog niemand aan tafel. Neem plaats om te spelen.",
    startHint: "Genoeg spelers — deel de eerste hand!",
    needPlayers: (n: number) => `Minstens ${n} spelers met fiches nodig.`,
    waitingToStart: "Wachten tot er gedeeld wordt…",
  },
  blackjack: {
    nav: "Blackjack",
    title: "Blackjack",
    subtitle: "Samen aan één tafel tegen de dealer — zo dicht mogelijk bij 21.",
    stat: "Jouw bibcoins",
    unavailable: "Blackjack is even niet beschikbaar.",
    busy: "Even te snel — probeer opnieuw.",
    roundInProgress: "De ronde is al bezig.",
    noRound: "Geen actieve ronde.",
    notYourTurn: "Het is niet jouw beurt.",
    alreadyBet: "Je hebt al ingezet deze ronde.",
    cantAfford: "Niet genoeg bibcoins voor die inzet.",
    join: "Ga zitten",
    leave: "Sta op",
    sitFirst: "Ga eerst zitten om mee te spelen.",
    empty: "Nog niemand aan tafel. Ga zitten 👇",
    betLabel: "Inzet",
    placeBet: "Inzetten",
    quickBet: {
      label: "Snel:",
      half: "½",
      double: "×2",
      allIn: "All-in",
    },
    deal: "Deel de kaarten",
    waitingDeal: "Wachten tot er gedeeld wordt…",
    bettingOpen: "Plaats je inzet voor deze ronde.",
    hit: "Kaart",
    stand: "Pas",
    double: "Verdubbel",
    split: "Split",
    newRound: "Nieuwe ronde",
    dealer: "Dealer",
    you: "Jij",
    bust: "Bust!",
    yourTurn: "Jouw beurt!",
    waitingFor: (name: string) => `Wachten op ${name}…`,
    dealerTurn: "De dealer speelt…",
    handLabel: (n: number) => `Hand ${n}`,
    betChip: (n: number) => `Inzet ${n}`,
    seatedCount: (n: number) => (n === 1 ? "1 speler" : `${n} spelers`),
    result: {
      win: "Gewonnen! 🎉",
      lose: "Verloren 😞",
      push: "Gelijk (push)",
      blackjack: "Blackjack! 🃏",
    },
    payoutNote: (n: number) => `+${n} bibcoins uitbetaald`,
    strategy: {
      toggle: "Spiekkaart",
      hide: "Verberg spiekkaart",
      hint: "Statistisch de beste zet: jouw hand vs. de open kaart van de dealer.",
      dealerHeader: "Dealer",
      hard: "Harde hand",
      soft: "Zachte hand (met aas)",
      pairs: "Paren (splitsen)",
      legend: {
        H: "Kaart",
        S: "Pas",
        D: "Verdubbel (anders kaart)",
        Ds: "Verdubbel (anders pas)",
        P: "Split",
      },
    },
  },
  keno: {
    title: "Keno",
    subtitle: "Kies tot 10 getallen; er worden er 10 getrokken. Meer raak = meer uit.",
    stat: "Jouw bibcoins",
    cantAfford: "Niet genoeg bibcoins voor deze inzet.",
    unavailable: "Keno is even niet beschikbaar.",
    betLabel: "Inzet",
    pickHint: (n: number, max: number) => `${n}/${max} gekozen`,
    clear: "Wissen",
    random: "Quick pick",
    play: "Speel",
    playing: "Trekken…",
    needPick: "Kies minstens één getal.",
    hits: (h: number, k: number) => `${h}/${k} raak`,
    resultWin: (m: number, payout: number) => `${m}× — +${payout} bibcoins 🎉`,
    resultLose: "Niks deze keer 😞",
    hint: "Kies je getallen en inzet, en speel.",
  },
  hilo: {
    title: "Hi-Lo",
    subtitle: "Is de volgende kaart hoger of lager? Bouw je multiplier op en cash uit voor je mis gokt.",
    stat: "Jouw bibcoins",
    cantAfford: "Niet genoeg bibcoins voor deze inzet.",
    unavailable: "Hi-Lo is even niet beschikbaar.",
    busy: "Even te snel — probeer opnieuw.",
    finishFirst: "Maak je huidige spel eerst af.",
    noGame: "Geen actief spel — start er eentje.",
    guessFirst: "Doe eerst een gok.",
    betLabel: "Inzet",
    start: "Start spel",
    newGame: "Nieuw spel",
    higher: "Hoger",
    lower: "Lager",
    multiplier: (m: number) => `${m.toFixed(2)}×`,
    chance: (p: number) => `${Math.round(p)}%`,
    cashout: (n: number) => `Cash uit · +${n}`,
    streak: (n: number) => `Streak ${n}`,
    potential: (n: number) => `Nu waard: ${n}`,
    cashedOut: (n: number) => `Uitgecasht: +${n} bibcoins 🎉`,
    busted: (card: string) => `💥 ${card} — fout gegokt!`,
    hint: "Kies je inzet en start. Zelfde kaart telt als juist gegokt.",
  },
  wheel: {
    title: "Wheel",
    subtitle: "Draai het rad; kies je risico. Hoe hoger het risico, hoe groter de multipliers.",
    stat: "Jouw bibcoins",
    cantAfford: "Niet genoeg bibcoins voor deze inzet.",
    unavailable: "Wheel is even niet beschikbaar.",
    betLabel: "Inzet",
    riskLabel: "Risico",
    risks: { low: "Laag", medium: "Middel", high: "Hoog" },
    spin: "Draai!",
    spinning: "Het rad draait…",
    multiplier: (m: number) => `${m}×`,
    resultWin: (m: number, payout: number) => `${m}× — +${payout} bibcoins 🎉`,
    resultLose: "0× — helaas, niks deze keer.",
    hint: "Kies je inzet en risico en draai het rad.",
  },
  lottery: {
    title: "Loterij",
    subtitle: "Koop tickets, de pot groeit en elke dag om 22:00 pakt één winnaar alles.",
    stat: "Jouw bibcoins",
    cantAfford: "Niet genoeg bibcoins voor zoveel tickets.",
    unavailable: "De loterij is even niet beschikbaar.",
    busy: "Even te snel — probeer opnieuw.",
    potLabel: "Pot",
    ticketPrice: (n: number) => `${n} / ticket`,
    buy: (n: number) => `Koop ${n} ${n === 1 ? "ticket" : "tickets"}`,
    yourTickets: (n: number) => `Jouw tickets: ${n}`,
    yourOdds: (p: number) => `Winkans: ${p.toFixed(0)}%`,
    drawAt: "Trekking elke dag om 22:00",
    drawIn: (h: number, m: number, s: number) =>
      `Trekking in ${h}u ${String(m).padStart(2, "0")}m ${String(s).padStart(2, "0")}s`,
    noTickets: "Nog geen tickets — koop de eerste.",
    participants: (n: number) => `${n} ${n === 1 ? "deelnemer" : "deelnemers"}`,
    youWon: (n: number) => `Je won de pot: +${n} bibcoins! 🎉`,
    lastWinner: (name: string, prize: number) =>
      `Vorige trekking: ${name} won ${prize} bibcoins 🎉`,
    round: (n: number) => `Ronde ${n}`,
  },
  roulette: {
    title: "Roulette",
    subtitle: "Zet samen in; na de timer draait het wiel automatisch voor iedereen.",
    stat: "Jouw bibcoins",
    cantAfford: "Niet genoeg bibcoins voor deze inzet.",
    unavailable: "Roulette is even niet beschikbaar.",
    busy: "Even te snel — probeer opnieuw.",
    betsLocked: "Inzetten gesloten — het wiel draait.",
    tableFull: "De tafel zit vol inzetten voor deze ronde.",
    spin: "Draai!",
    spinNow: "Spin nu",
    spinning: "Het wiel draait…",
    clear: "Wissen",
    chip: "Fiche",
    totalBet: (n: number) => `Inzet: ${n}`,
    noBets: "Plaats eerst een inzet.",
    waitingFirstBet: "Plaats de eerste inzet om de timer te starten.",
    bettingEndsIn: (s: number) => `Inzetten sluit in ${s}s`,
    nextRound: "Volgende ronde begint zo…",
    yourStake: (n: number) => `Jouw inzet: ${n}`,
    yourResultWin: (payout: number) => `Je wint +${payout} bibcoins! 🎉`,
    yourResultLose: "Niks deze keer 😞",
    winningNumber: (n: number) => `Winnend nummer: ${n}`,
    resultWin: (num: number, payout: number) =>
      `${num} — gewonnen! +${payout} bibcoins 🎉`,
    resultLose: (num: number) => `${num} — helaas, niks deze keer.`,
    labels: {
      even: "EVEN",
      odd: "ONEVEN",
      low: "1–18",
      high: "19–36",
      red: "ROOD",
      black: "ZWART",
      dozen1: "1e 12",
      dozen2: "2e 12",
      dozen3: "3e 12",
      column: "2:1",
    },
  },
  mines: {
    title: "Mines",
    subtitle:
      "Open tegels, ontwijk de bommen en cash uit voor je er één raakt. Meer bommen = hogere multiplier.",
    stat: "Jouw bibcoins",
    cantAfford: "Niet genoeg bibcoins voor deze inzet.",
    unavailable: "Mines is even niet beschikbaar.",
    busy: "Even te snel — probeer opnieuw.",
    finishFirst: "Maak je huidige spel eerst af.",
    noGame: "Geen actief spel — start er eentje.",
    revealFirst: "Open eerst minstens één tegel.",
    betLabel: "Inzet",
    minesLabel: "Aantal bommen",
    minesValue: (n: number) => `${n} ${n === 1 ? "bom" : "bommen"}`,
    start: "Start spel",
    cashout: (n: number) => `Cash uit · +${n}`,
    cashoutDisabled: "Cash uit",
    newGame: "Nieuw spel",
    boom: "💥 Boem! Je raakte een bom.",
    cashedOut: (n: number) => `Uitgecasht: +${n} bibcoins 🎉`,
    allClear: "Alles veilig! Maximale winst 🎉",
    multiplier: (m: number) => `${m.toFixed(2)}×`,
    nextMultiplier: (m: number) => `Volgende tegel: ${m.toFixed(2)}×`,
    potential: (n: number) => `Nu waard: ${n}`,
    safe: (found: number, total: number) => `${found}/${total} veilig`,
    hint: "Kies je inzet en aantal bommen, en start het spel.",
  },
  plinko: {
    title: "Plinko",
    subtitle:
      "Laat een bal vallen door de pinnen. Hoe dichter bij de rand hij landt, hoe hoger de multiplier.",
    stat: "Jouw bibcoins",
    cantAfford: "Niet genoeg bibcoins voor deze inzet.",
    unavailable: "Plinko is even niet beschikbaar.",
    minBet: (n: number) => `Minimuminzet is ${n} bibcoins.`,
    betLabel: "Inzet",
    rowsLabel: "Rijen",
    riskLabel: "Risico",
    drop: "Laat vallen",
    dropN: (n: number) => (n === 1 ? "Laat vallen" : `Laat ${n} vallen`),
    dropping: "Valt…",
    ballsLabel: "Ballen",
    ballsValue: (n: number) => `${n} ${n === 1 ? "bal" : "ballen"}`,
    inFlight: (n: number) => `${n} in de lucht…`,
    risks: { low: "Laag", medium: "Middel", high: "Hoog" },
    rowsValue: (n: number) => `${n} rijen`,
    multiplier: (m: number) => `${m}×`,
    landedWin: (m: number, payout: number) =>
      `${m}× — +${payout} bibcoins 🎉`,
    landedLose: (m: number) => `${m}× — helaas, niks deze keer.`,
    recent: "Laatste",
    hint: "Kies je inzet, aantal rijen en risico, en laat de bal vallen.",
  },
  crash: {
    title: "Crash",
    subtitle:
      "Lanceer de raket en cash uit vóór hij ontploft. Hoe langer je wacht, hoe hoger de multiplier — maar hij kan élk moment crashen.",
    stat: "Jouw bibcoins",
    cantAfford: "Niet genoeg bibcoins voor deze inzet.",
    unavailable: "Crash is even niet beschikbaar.",
    busy: "Even te snel — probeer opnieuw.",
    noRound: "Geen actieve ronde.",
    betLabel: "Inzet",
    launch: "Lanceer 🚀",
    cashout: (m: string) => `Cash uit · ${m}×`,
    potentialLabel: "Nu waard",
    resultWin: (m: string, payout: number) =>
      `Uitgecasht op ${m}× — +${payout} bibcoins 🎉`,
    resultLose: (crash: string) => `💥 Gecrasht op ${crash}× — helaas.`,
    recent: "Laatste",
    hint: "Kies je inzet en lanceer de raket.",
  },
  pillory: {
    title: "Aan de schandpaal",
    set: (name: string) => `${name} staat aan de schandpaal 🔨`,
    cleared: (name: string) => `${name} mag van de schandpaal af.`,
    cmdHint: "Gebruik: /schandpaal <naam> [reden] — kost 250 bibcoins",
    cantAffordSet: "Niet genoeg bibcoins om iemand op de schandpaal te zetten.",
    buyOff: (cost: number) => `Koop jezelf vrij (${cost})`,
    boughtOff: "Je bent van de schandpaal af 🎉",
    cantAfford: "Niet genoeg bibcoins om jezelf vrij te kopen.",
    notOnIt: "Je staat niet op de schandpaal.",
    tooSoon: (mins: number) =>
      `Je moet minstens een uur blijven — nog ${mins} min.`,
    lockedFor: (mins: number) => `Vrijkopen kan over ${mins} min`,
    buyOffHint: (cost: number) => `daarna ${cost} bibcoins`,
    silenced: "Je staat aan de schandpaal — je kan even niet stemmen.",
  },
  foodBets: {
    title: "Waar eten we? (zet bibcoins in)",
    cantAfford: "Niet genoeg bibcoins.",
    error: "Inzetten mislukt. Probeer opnieuw.",
    placePlaceholder: "Plek (bv. Frituur, Pizza)",
    amountPlaceholder: "Inzet",
    amountHint: "Kies je inzet en druk op + bij een plek, of tik een nieuwe plek.",
    stake: "Zet in",
    yourStake: (n: number) => `jij ${n}`,
    empty: "Nog niks ingezet — zet de eerste plek in.",
    staked: (n: number) => `+${n} ingezet 🍽️`,
  },
  quests: {
    title: "Dagelijkse quests",
    subtitle: "Voltooi mini-doelen en pak je bibcoins. Reset elke dag.",
    unavailable: "Quests zijn even niet beschikbaar.",
    error: "Er ging iets mis. Probeer opnieuw.",
    notReady: "Nog niet voltooid (of al geclaimd).",
    claim: (n: number) => `Claim +${n}`,
    claimed: "Geclaimd ✅",
    reward: (n: number) => `+${n}`,
    progress: (done: number, goal: number) =>
      `${Math.min(done, goal)}/${goal}`,
    claimedToast: (n: number) => `Quest voltooid: +${n} bibcoins 🎉`,
    streakTitle: "Login-streak",
    streakDays: (n: number) => `${n} ${n === 1 ? "dag" : "dagen"} 🔥`,
    streakNext: (n: number) => `Morgen: +${n}`,
    streakNone: "Open de app elke dag voor een oplopende bonus (tot +500).",
  },
  marketplace: {
    title: "Klussenmarkt",
    subtitle:
      "Zet jezelf te huur of vraag een klusje — betaal en verdien in bibcoins.",
    error: "Er ging iets mis. Probeer opnieuw.",
    unavailable: "De markt is even niet beschikbaar.",
    gone: "Dit aanbod bestaat niet meer.",
    alreadyHired: "Te laat — al ingehuurd.",
    ownOffer: "Dit is je eigen plaatsing.",
    cantAfford: "Niet genoeg bibcoins.",
    // Create form
    newTitle: "Nieuwe plaatsing",
    kindOffer: "Ik bied aan",
    kindRequest: "Ik zoek",
    kindOfferHint: "Bied een klusje aan; iemand huurt je in en betaalt jou.",
    kindRequestHint: "Vraag een klusje; anderen bieden en jij betaalt de winnaar.",
    titleLabel: "Titel",
    titlePlaceholder: "bv. Waterfles vullen",
    descLabel: "Beschrijving",
    descPlaceholder: "bv. Ik vul je waterfles bij de fontein.",
    priceLabel: "Prijs",
    budgetLabel: "Budget",
    presetsLabel: "Snelkeuze",
    post: "Plaatsen",
    posting: "Plaatsen…",
    posted: "Geplaatst 📌",
    // Offer card
    byline: "door",
    coins: (n: number) => `${n} bibcoins`,
    hire: (n: number) => `Huur in · ${n}`,
    cancel: "Intrekken",
    complete: "Markeer klaar",
    open: "Open",
    hiredBy: (name: string) => `Ingehuurd door ${name}`,
    youHired: "Jij huurde dit in",
    acceptedFrom: (name: string) => `Toegewezen aan ${name}`,
    done: "✅ Klaar",
    hiredToast: (n: number) => `Ingehuurd — ${n} bibcoins betaald 🪙`,
    paidToast: (name: string, n: number) => `${name} betaald: ${n} bibcoins 🪙`,
    // Bids
    bidsLabel: "Biedingen",
    noBids: "Nog geen biedingen.",
    bidPlaceholder: "Jouw prijs",
    bid: "Bied",
    yourBid: (n: number) => `Jouw bod: ${n}`,
    withdrawBid: "Bod intrekken",
    accept: "Accepteer",
    bidPlaced: "Bod geplaatst 🙋",
    empty: "Nog niks op de markt — plaats de eerste klus.",
  },
  theft: {
    unavailable: "Stelen is even niet beschikbaar.",
    notYourself: "Je kan niet van jezelf stelen.",
    cooldown: "Rustig aan, dief — je moet even wachten voor je weer steelt.",
    alreadyOpen: "Je hebt al een openstaande diefstal bij die persoon.",
    victimBroke: "Die persoon heeft niet genoeg bibcoins.",
    stole: (amount: number, name: string) =>
      `Je stal ${amount} van ${name} 🥷`,
    badAmount: "Geef een geldig bedrag op.",
    button: "Stelen",
    dialogTitle: (name: string) => `Stelen van ${name}`,
    amountLabel: "Hoeveel wil je stelen?",
    victimHas: (n: number) => `${n} bibcoins beschikbaar`,
    warning:
      "Pas op: ziet de ander het en claimt hij op tijd, dan betaal je het dubbele terug.",
    steal: "Steel",
    stealing: "Stelen…",
    bannerTitle: "Je bent bestolen! 🥷",
    bannerBody: (amount: number) =>
      `Er is ${amount} van je gestolen. Claim het vóór je volgende uitgave — dan krijg je het dubbele terug.`,
    claimButton: "Ik ben bestolen",
    claimed: (amount: number) => `Dief gepakt! +${amount} bibcoins 💰`,
    tooLate: "Te laat — je had al iets uitgegeven. De dief houdt de buit.",
    falseClaim: (amount: number) =>
      `Je was niet bestolen. Boete: ${amount} bibcoins naar het casino.`,
  },
  stock: {
    title: "BIB-aandeel",
    subtitle:
      "Koop een aandeel in het casino. De koers stijgt als spelers verliezen (het huis wint) en daalt als spelers winnen.",
    stat: "Jouw aandelen",
    price: "Koers",
    priceUnit: (n: number) => `${n.toLocaleString("nl-BE")} bibcoins`,
    perShare: "/ aandeel",
    buy: "Kopen",
    sell: "Verkopen",
    qtyLabel: "Aantal aandelen",
    yourShares: "Jouw aandelen",
    yourValue: "Waarde",
    avgPrice: "Gem. aankoop",
    pnl: "Winst/verlies",
    outstanding: "Aandelen in omloop",
    houseProfit: "Huiswinst",
    wagered: "Totaal vergokt",
    cantAfford: "Niet genoeg bibcoins voor deze aankoop.",
    notEnoughShares: "Je hebt niet genoeg aandelen om te verkopen.",
    busy: "Even druk op de beurs — probeer opnieuw.",
    unavailable: "De beurs is even niet beschikbaar.",
    bought: (qty: number, cost: number) =>
      `${qty} ${qty === 1 ? "aandeel" : "aandelen"} gekocht voor ${cost} bibcoins 📈`,
    sold: (qty: number, proceeds: number) =>
      `${qty} ${qty === 1 ? "aandeel" : "aandelen"} verkocht voor ${proceeds} bibcoins 💰`,
    empty: "Nog geen koersgeschiedenis — wees de eerste die instapt.",
    balance: "Saldo",
    hint: "De koers volgt de winst van het casino: hoe meer er verloren wordt aan de tafels, hoe meer jouw aandeel waard wordt.",
  },
  dice: {
    title: "Dice",
    subtitle:
      "Versleep de grens en gok of de worp eronder of erboven valt. Kleinere kans = hogere multiplier.",
    stat: "Jouw bibcoins",
    cantAfford: "Niet genoeg bibcoins voor deze inzet.",
    unavailable: "Dice is even niet beschikbaar.",
    betLabel: "Inzet",
    roll: "Gooi",
    rolling: "Gooien…",
    over: "Erboven",
    under: "Eronder",
    multiplierLabel: "Multiplier",
    multiplier: (m: number) => `${m.toFixed(2)}×`,
    winChanceLabel: "Winkans",
    winChance: (p: number) => `${p.toFixed(2)}%`,
    payoutLabel: "Uitbetaling",
    resultWin: (roll: string, payout: number) =>
      `${roll} — gewonnen! +${payout} bibcoins 🎉`,
    resultLose: (roll: string) => `${roll} — helaas, niks deze keer.`,
    half: "½",
    double: "2×",
    hint: "Versleep de grens, kies boven/onder en gooi.",
  },
  petconnect: {
    title: "Pet Connect",
    subtitle:
      "Verbind twee gelijke diertjes (max 2 bochten) en ruim het bord leeg.",
    stat: "Beste score",
    newGame: "Nieuw spel",
    shuffle: "Schudden",
    shuffleHint: "Geen zetten meer — schud het bord.",
    won: (score: number) => `Bord leeg! Score ${score} 🎉`,
    seconds: (s: number) => `${s}s`,
    left: (n: number) => `${n} over`,
  },
  steps: {
    title: "Stappen vergelijken",
    subtitle:
      "Stuur je dagtotaal aan stappen naar BibSync en vergelijk met de groep.",
    manualTitle: "Geen iPhone? Tel hier",
    manualSubtitle:
      "Tel via de bewegingssensor — dan moet je wel deze pagina open houden tijdens je pauze.",
    start: "Start met tellen",
    stop: "Stop & opslaan",
    saving: "Opslaan…",
    counting: "Aan het tellen — steek je telefoon op zak en wandel.",
    hint: "Houd deze pagina open tijdens het tellen. We gebruiken de bewegingssensor van je telefoon.",
    saved: (n: number) => `${n} stappen opgeslagen! 👟`,
    denied:
      "Geen toegang tot de bewegingssensor. Sta beweging & oriëntatie toe in je browserinstellingen.",
    unsupported:
      "Je toestel of browser ondersteunt de stappenteller niet. Gebruik de Apple Health-koppeling hierboven.",
    board: {
      title: "Ranglijst",
      today: "Vandaag",
      allTime: "Aller tijden",
      empty: "Nog niemand heeft stappen geteld.",
      unit: (n: number) => n.toLocaleString("nl-BE"),
    },
    health: {
      title: "Stuur je Apple Health-stappen",
      intro:
        "Koppel één keer met een Apple Shortcut. Daarna stuurt je iPhone je dagtotaal — je hoeft niets open te houden.",
      noService:
        "Health-koppeling is niet beschikbaar (server niet geconfigureerd).",
      generate: "Genereer mijn koppelcode",
      regenerate: "Nieuwe koppelcode",
      noToken: "Genereer eerst je koppelcode om de shortcut in te stellen.",
      copy: "Kopiëren",
      copyCode: "Kopieer koppelcode",
      copied: "Gekopieerd ✓",
      addToShortcuts: "Voeg toe aan Shortcuts",
      oneTapTitle: "In 2 tikken klaar:",
      oneTapSteps: [
        "Kopieer je koppelcode hieronder.",
        "Tik 'Voeg toe aan Shortcuts' en plak de code wanneer Shortcuts erom vraagt.",
        "Klaar — start de shortcut na je pauze, of laat 'm dagelijks automatisch lopen.",
      ],
      notReady:
        "De kant-en-klare shortcut is nog niet ingesteld. Gebruik zolang 'handmatig instellen' hieronder.",
      warning:
        "Deel je koppelcode met niemand — wie hem heeft, kan stappen op jouw naam insturen.",
      manualTitle: "Handmatig instellen",
      endpointLabel: "Endpoint (POST)",
      codeLabel: "Jouw koppelcode",
      bodyLabel: "JSON-body (vervang het stappen-getal)",
      steps: [
        "Open de Opdrachten-app (Shortcuts) op je iPhone en maak een nieuwe opdracht.",
        "Voeg 'Zoek gezondheidsmonsters' toe: type Stappen, periode Vandaag.",
        "Voeg 'Statistiek berekenen' toe met bewerking Som — dat is je dagtotaal.",
        "Voeg 'Inhoud van URL ophalen' toe: methode POST, met de endpoint hierboven.",
        "Zet de JSON-body zoals hieronder en vervang het stappen-getal door het resultaat uit de vorige stap.",
        "Bewaar de opdracht. Start ze na je pauze, of automatiseer ze dagelijks.",
      ],
    },
  },
  proposals: {
    title: "Pauzevoorstellen",
    new: "Nieuw voorstel",
    empty: "Nog geen pauzevoorstellen. Doe een voorstel 👇",
    slots: {
      title: "Vaste momenten",
      free: "Vrije voorstellen",
      breakAt: "Pauze om",
      defaultNote: "standaard — nog geen voorkeuren",
      defaultLabel: "standaard",
      notDecided: "Nog geen pauze",
      notDecidedSub: "Niemand heeft gestemd — geef je voorkeur of stem hieronder.",
      otherDays: "Voorstellen op andere dagen",
      yourPref: "Jouw voorkeur",
      save: "Opslaan",
      clear: "Wissen",
      saved: "Voorkeur opgeslagen.",
      empty: "Nog geen voorkeuren — geef de jouwe of stem op de standaard.",
      earlier: "Eerdere momenten",
    },
    form: {
      title: "Pauze voorstellen",
      typeLabel: "Type",
      dateLabel: "Datum",
      timeLabel: "Starttijd",
      hour: "Uur",
      minute: "Minuten",
      durationLabel: "Duur",
      destinationLabel: "Bestemming (optioneel)",
      destinationPlaceholder: "bv. Park, bakker — leeg = gewoon pauze (Okay)",
      walkLabel: "Wandeling 🚶",
      fixedSlotHint: (label: string) =>
        `Rond dit tijdstip is er het vaste moment "${label}". Stem daar op — een vrij voorstel kan hier niet.`,
      placesLabel: "Eerder gebruikt",
      noteLabel: "Notitie (optioneel)",
      notePlaceholder: "bv. afspraak aan de hoofdingang",
      submit: "Voorstel plaatsen",
      submitting: "Plaatsen…",
    },
    destinationBy: "📍",
    walkBy: "🚶",
    route: {
      plot: "Route op kaart",
      points: (n: number) => `Route · ${n} ${n === 1 ? "punt" : "punten"}`,
      view: (n: number) => `🗺️ Route (${n})`,
      hint: "Klik op de kaart om punten te plaatsen.",
      undo: "Stap terug",
      clear: "Route wissen",
    },
    types: {
      lunch: "Lunch",
      dinner: "Avondeten",
      coffee: "Pauze",
      other: "Andere",
    },
    duration: (min: number) =>
      min >= 60
        ? `${min / 60} u${min % 60 ? ` ${min % 60} min` : ""}`
        : `${min} min`,
    today: "Vandaag",
    tomorrow: "Morgen",
    winner: "Beslist",
    freeProposal: "Vrij voorstel",
    created: "Voorstel geplaatst.",
    deleted: "Voorstel verwijderd.",
    deleteConfirm: "Dit voorstel verwijderen?",
    by: "door",
    calendar: {
      day: "Dag",
      week: "Week",
      month: "Maand",
      today: "Vandaag",
      prev: "Vorige",
      next: "Volgende",
      emptyRange: "Geen voorstellen in deze periode.",
    },
    comments: {
      title: "Reacties",
      placeholder: "Schrijf een reactie…",
      send: "Plaats",
      empty: "Nog geen reacties.",
      toggle: (n: number) =>
        n === 0
          ? "Reageren"
          : `${n} ${n === 1 ? "reactie" : "reacties"}`,
      error: "Reactie niet geplaatst. Probeer opnieuw.",
    },
    votes: {
      yes: "Ja",
      maybe: "Misschien",
      no: "Nee",
      noVotes: "Nog geen stemmen",
      error: "Stem niet opgeslagen. Probeer opnieuw.",
      presentBasis: (n: number) =>
        `van ${n} ${n === 1 ? "persoon" : "mensen"} ter plaatse`,
    },
    validation: {
      dateInPast: "Kies vandaag of een datum in de toekomst.",
      dateTooFar: "Kies een datum binnen 7 dagen.",
      timeQuarter: "Starttijd moet op het kwartier vallen.",
      durationInvalid: "Kies een geldige duur.",
      noteTooLong: "Notitie mag max 200 tekens zijn.",
      slotTaken:
        "Er staat al een voorstel op dit tijdstip. Kies een ander moment.",
      useFixedSlot: (label: string) =>
        `Dit valt onder het vaste moment "${label}". Stem daar i.p.v. een vrij voorstel te plaatsen.`,
      notPresent:
        "Check eerst in (of deel je locatie) — alleen aanwezigen kunnen voorstellen en stemmen.",
    },
    presentRequired:
      "Check in of deel je locatie om voorstellen te plaatsen, te stemmen en te reageren.",
  },
  presence: {
    title: "Wie is er?",
    empty: "Nog niemand actief.",
    yourStatus: "Jouw status",
    backAt: "Terug om",
    backAtLabel: "Terug om (optioneel)",
    lastSeen: (time: string) => `laatst gezien om ${time}`,
    updated: "Status bijgewerkt.",
    statuses: {
      studying: "Aan het studeren",
      break: "Pauze",
      lunch: "Lunch",
      away: "Weg",
      done: "Klaar voor vandaag",
    },
    location: {
      here: "📍 ter plaatse",
      away: "📍 niet ter plaatse",
      on: "📍 Aanwezigheid via locatie staat aan",
      checking: "📍 Locatie controleren…",
      denied:
        "📍 Locatie geweigerd — sta locatie toe in je browser om aanwezigheid te tonen.",
      unsupported: "📍 Locatie wordt niet ondersteund door deze browser.",
      error: "📍 Locatie kon niet bepaald worden.",
      retry: "Opnieuw proberen",
      notSet: "📍 Geen locatie ingesteld voor deze room.",
      notSetManage: "Stel ze in bij instellingen om aanwezigheid te meten.",
    },
    checkIn: {
      prompt: "Vandaag in de bib?",
      action: "Ik ben er",
      done: "✓ Aanwezig vandaag",
      undo: "Toch niet",
      here: "✓ aanwezig",
    },
  },
  chat: {
    title: "Chat",
    empty: "Nog geen berichten — zeg hallo 👋",
    placeholder: "Schrijf een bericht…",
    send: "Versturen",
    sending: "Verzendt…",
    loadMore: "Laad oudere berichten",
    newMessages: (n: number) =>
      `${n} ${n === 1 ? "nieuw bericht" : "nieuwe berichten"} ↓`,
    unreadLabel: (n: number) =>
      `${n} ongelezen ${n === 1 ? "bericht" : "berichten"}`,
    error: "Bericht niet verzonden. Probeer opnieuw.",
    typing: (name: string) => `${name} is aan het typen…`,
    typingTwo: (a: string, b: string) => `${a} en ${b} zijn aan het typen…`,
    typingMany: "Meerdere mensen zijn aan het typen…",
    edit: "Bewerk",
    delete: "Verwijder",
    edited: "bewerkt",
    save: "Opslaan",
    cancel: "Annuleer",
    rainbowOn: "🌈 Full rainbow mode aan!",
    rainbowOff: "Rainbow mode uit.",
    snakeBotOn: "😈 Cheatcodes aan — open Snake, hij speelt vanzelf perfect.",
    snakeBotOff: "Cheatcodes uit.",
    boardHonestOn: "🧐 Leaderboard op eerlijk gezet — cheat-scores verborgen voor iedereen.",
    boardAllOn: "🤖 Leaderboard toont weer alle scores (incl. cheats) voor iedereen.",
    react: "Reageer",
    gif: {
      button: "GIF kiezen",
      title: "Kies een GIF",
      search: "Zoek een GIF…",
      empty: "Geen GIFs gevonden.",
      poweredBy: "Powered by GIPHY",
    },
    photo: {
      button: "Foto sturen",
      invalid: "Kies een afbeelding.",
      tooLarge: "Afbeelding mag max 5 MB zijn.",
      error: "Uploaden mislukt. Probeer opnieuw.",
      expired: "📷 foto verlopen (na 3 dagen)",
    },
  },
  games: {
    nav: "Games",
    title: "Spelletjes",
    subtitle: "Speel tegen je medestudenten",
    play: "Speel",
    yourBest: "Jouw beste",
    noBest: "—",
    leaderboard: "Leaderboard",
    sessionBoard: {
      title: "Laatste sessie 🎲",
      subtitle:
        "Netto winst/verlies van ieders recentste goksessie (roulette, blackjack & poker).",
      empty: "Nog niemand heeft recent gegokt.",
      meta: (rounds: number, when: string) =>
        `${rounds} ${rounds === 1 ? "ronde" : "rondes"} · ${when}`,
    },
    noScores: "Nog niemand heeft gespeeld.",
    submitError: "Score kon niet opgeslagen worden.",
    honestView: "eerlijke weergave",
    cheatedTag: "Met cheats behaald",
    king: {
      tooltip: (label: string, n: number) =>
        `${label} · +${n} bibcoins/dag 👑`,
      snake: "Snake King",
      flappy: "Flappy King",
      tetris: "Tetris King",
      twenty48: "2048 King",
      petconnect: "Pet Connect King",
    },
    snake: {
      title: "Snake",
      subtitle: "Klassiek — pijltjes of WASD om te draaien",
      score: "Score",
      gameOver: "Game over",
      restart: "Opnieuw",
      newHighScore: "Nieuwe high score!",
      saved: (n: number) => `Score ${n} opgeslagen`,
      saveResult: "Result opslaan",
      mobileBlocked:
        "Snake is enkel speelbaar op desktop — kom terug op een laptop.",
    },
    cap: {
      label: "Coins dit uur",
      resetIn: (m: number, s: number) =>
        `Reset over ${m}m ${s.toString().padStart(2, "0")}s`,
    },
    poker: {
      title: "Poker",
      subtitle: "Texas Hold'em met je bibcoins tegen elkaar",
      stat: "Jouw bibcoins",
    },
    flappy: {
      title: "Flappy Bird",
      subtitle: "Tik/spatie om te fladderen. Coins per buis (gedeelde uurcap).",
      score: "Score",
      best: "Record",
      tapToStart: "Tik of spatie om te starten",
      gameOver: "Game over",
      restart: "Opnieuw",
      saved: (n: number) => `Score ${n} opgeslagen`,
      newBest: "Nieuw record! 🎉",
    },
    tetris: {
      title: "Tetris",
      subtitle: "Maak rijen vol — coins per rij",
      score: "Rijen",
      controls: "Pijltjes om te bewegen, ↑ draaien, spatie laten vallen",
      gameOver: "Game over",
      restart: "Opnieuw",
      newHighScore: "Nieuwe high score!",
      saved: (n: number) => `${n} rijen opgeslagen`,
      left: "Links",
      right: "Rechts",
      rotate: "Draai",
      drop: "Laten vallen",
    },
    twenty48: {
      title: "2048",
      subtitle: "Veeg en combineer — coins per nieuwe tegel",
      score: "Hoogste tegel",
      controls: "Pijltjes of vegen om te schuiven",
      gameOver: "Geen zetten meer",
      restart: "Opnieuw",
      newHighScore: "Nieuwe high score!",
      saved: (n: number) => `Tegel ${n} bereikt`,
    },
  },
  pwa: {
    title: "Installeer als app",
    subtitle:
      "Voeg BibSync toe aan je beginscherm voor snelle, full-screen toegang.",
    install: "Installeren",
    iosHint:
      'Tik op het Deel-icoon (vierkant met pijl) en kies "Zet op beginscherm".',
    genericHint:
      'Open deze site op je telefoon in Chrome of Safari en kies "Toevoegen aan beginscherm".',
  },
  push: {
    title: "Meldingen",
    subtitle: "Krijg een melding op dit toestel bij nieuwe voorstellen.",
    enable: "Meldingen aanzetten",
    disable: "Meldingen uitzetten op dit toestel",
    enabledToast: "Meldingen aangezet 🔔",
    disabledToast: "Meldingen uitgezet.",
    denied:
      "Meldingen zijn geblokkeerd. Zet ze aan in je browser-/systeeminstellingen.",
    unsupported:
      "Meldingen worden hier niet ondersteund. Op iPhone: installeer eerst de app (Zet op beginscherm).",
    error: "Kon meldingen niet instellen. Probeer opnieuw.",
    prefProposals: "Nieuwe pauzevoorstellen",
    prefChat: "Nieuwe chatberichten",
    prefComments: "Reacties op mijn voorstellen",
    prefVotes: "Stemmen op mijn voorstellen",
    prefMarket: "Klussenmarkt (bod / inhuur)",
    newProposal: "Nieuw pauzevoorstel",
    newMessage: "Nieuw bericht",
    mention: (name: string) => `${name} noemde je 💬`,
    newComment: "Nieuwe reactie op je voorstel",
    newVote: "Nieuwe stem op je voorstel",
    marketBid: (name: string) => `${name} bood op je verzoek 🙋`,
    marketHired: (name: string) => `${name} huurde je klus in 🤝`,
    marketAccepted: "Je bod is geaccepteerd 🎉",
    gifMessage: "📷 GIF",
  },
  bibcoins: {
    name: "bibcoins",
    balance: (n: number) => `${n} bibcoins`,
    hourlyGranted: (n: number) => `+${n} bibcoins ⏳`,
    dailyGranted: (n: number) => `Dagbonus: +${n} bibcoins 🎁`,
    strijderGranted: (n: number) => `Strijder bonus: +${n} bibcoins 🌙⚔️`,
    strijder: {
      title: "Strijder bonus 🌙⚔️",
      body: "Je bent online tussen 00:30 en 01:30 — echte nacht-strijder! Pak je 1000 bibcoins.",
      claim: "Claim +1000",
      later: "Later",
    },
    transfer: {
      button: "Stuur bibcoins",
      title: (name: string) => `Stuur bibcoins naar ${name}`,
      amountLabel: "Bedrag",
      send: "Versturen",
      sending: "Versturen…",
      self: "Je kan geen bibcoins naar jezelf sturen.",
      noUser: "Die gebruiker bestaat niet.",
      failed: "Versturen mislukt — niet genoeg bibcoins?",
      success: (n: number, name: string) => `${n} bibcoins naar ${name} 🪙`,
    },
    wealth: {
      title: "Rijkste in de room",
      empty: "Nog geen ranglijst.",
    },
    earn: {
      button: "Hoe verdien ik bibcoins?",
      title: "Bibcoins verdienen",
      subtitle: "Zo spaar je bibcoins — helemaal zonder te gokken.",
      back: "Terug naar de shop",
      perDay: (n: number) => `+${n} / dag`,
      perHour: (n: number) => `+${n} / uur`,
      flat: (n: number) => `+${n}`,
      perPoint: (n: number) => `+${n} / punt`,
      per1000: (n: number) => `+${n} / 1000`,
      bonus: "bonus",
      methods: {
        dailyTitle: "Dagelijkse bonus",
        dailyDesc: "Open de app elke dag en pak je login-bonus.",
        hourlyTitle: "Elk uur",
        hourlyDesc:
          "Automatisch voor elk uur dat voorbijgaat (tot 48 uur sparen).",
        strijderTitle: "Strijder bonus 🌙",
        strijderDesc:
          "Wees online tussen 00:30 en 01:30 — voor de echte nacht-strijders. Eén keer per dag.",
        proposalTitle: "Een pauze voorstellen",
        proposalDesc:
          "Doe een voorstel in een room. Eén keer per dag per room — spammen helpt niet.",
        commentTitle: "Reageren",
        commentDesc:
          "Plaats een reactie op een voorstel. Eén keer per dag per room.",
        voteTitle: "Stemmen",
        voteDesc: "Stem op een voorstel. Per voorstel één keer.",
        chatTitle: "Chatten",
        chatDesc: "Stuur 20 berichten op één dag.",
        snakeTitle: "Snake",
        snakeDesc: "Verdien coins per appel, elke ronde (gedeelde uurcap).",
        petTitle: "Pet Connect",
        petDesc: "Ruim een volledig bord leeg (één keer per dag).",
        stepsTitle: "Stappen",
        stepsDesc: "Per 1000 stappen op een dag (tot 20.000 stappen).",
        achievementsTitle: "Achievements",
        achievementsDesc: "Eenmalige bonussen voor mijlpalen — zie je profiel.",
      },
    },
    shop: {
      nav: "Shop",
      title: "Shop",
      subtitle: "Geef je bibcoins uit aan cosmetica voor je avatar.",
      buy: "Kopen",
      owned: "In bezit",
      equip: "Dragen",
      equipped: "Uitgerust",
      unequip: "Afdoen",
      bought: "Gekocht! 🎉",
      cantAfford: "Niet genoeg bibcoins.",
      error: "Aankoop mislukt. Probeer opnieuw.",
      empty: "Nog geen items in deze categorie.",
      none: "Geen",
    },
    achievements: {
      title: "Achievements",
      locked: "Nog niet behaald",
      reward: (n: number) => `+${n}`,
      empty: "Nog geen achievements behaald.",
    },
    cosmeticTypes: {
      frame: "Frames",
      color: "Naamkleuren",
      badge: "Badges",
      accessory: "Accessoires",
      pet: "Pets",
      title: "✨ Titels (premium)",
      effect: "🌈 Naam-effecten (premium)",
    },
  },
} as const;
