/**
 * Horse name pool — content data (like the voetbal categories), not UI copy.
 * Six distinct names are drawn per race from the race's `name_seed`, so every
 * client shows the same line-up. Client-safe.
 */
export const HORSE_NAME_POOL = [
  "Bliksem",
  "Donder",
  "Stormwind",
  "Wervelwind",
  "Kanonskogel",
  "Raket Rik",
  "Turbo Truus",
  "Snelle Eddy",
  "Vlam",
  "Komeet",
  "Hoefijzer Henk",
  "Galop Gerda",
  "Don Galoppo",
  "Madame Cheval",
  "Sjokkende Sjarel",
  "Slome Jos",
  "Bonkie",
  "Knabbel",
  "Bibliotheekbeest",
  "Blokbeest",
  "Studiebreak",
  "Pauze Paula",
  "Cafeïne",
  "Deadline",
  "Procrastinatie",
  "Examenstress",
  "Herkansing",
  "Cum Laude",
  "Tentamen Tom",
  "Syllabus Sara",
  "Motivatie",
  "Burn-out Bert",
  "Uitstelgedrag",
  "Nachtbraker",
  "Spiekbriefje",
  "Puntenpakker",
  "Bissende Bart",
  "Erasmus Express",
  "Fraude Freddy",
  "Wisselstress",
] as const;
