/**
 * One-off generator: scripts/us-states-source.js -> src/lib/usstates/map.ts
 *
 * Source: @svg-maps/usa (MIT) — `export default { viewBox, locations: [{name,id,path}] }`
 * where `id` is the lowercase 2-letter postal code (plus "dc", which we drop so
 * only the 50 states remain). US state borders are factual geographic data; the
 * @svg-maps file is MIT-licensed.
 *
 * The paths use relative commands, so a label anchor cannot be read off the raw
 * numbers — we walk the path keeping the absolute pen position, then take the
 * polygon (area) centroid of the sampled vertices (falling back to the vertex
 * average for degenerate rings).
 *
 * Run: node scripts/build-us-map.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";

const SRC = new URL("./us-states-source.js", import.meta.url);
const OUT = new URL("../src/lib/usstates/map.ts", import.meta.url);

const raw = readFileSync(SRC, "utf8")
  .replace(/^\s*export\s+default\s*/, "")
  .replace(/;\s*$/, "");
const data = JSON.parse(raw);

/** Walk an SVG path `d` and return the absolute (x,y) vertices it passes through. */
function absolutePoints(d) {
  const tokens = d.match(/[a-zA-Z]|-?\d*\.?\d+(?:e[-+]?\d+)?/gi) ?? [];
  const pts = [];
  let i = 0;
  let cmd = "M";
  let x = 0;
  let y = 0;
  let startX = 0;
  let startY = 0;
  const num = () => parseFloat(tokens[i++]);
  while (i < tokens.length) {
    if (/[a-zA-Z]/.test(tokens[i])) cmd = tokens[i++];
    const rel = cmd === cmd.toLowerCase();
    const C = cmd.toUpperCase();
    if (C === "M") {
      let nx = num();
      let ny = num();
      if (rel) {
        nx += x;
        ny += y;
      }
      x = nx;
      y = ny;
      startX = x;
      startY = y;
      pts.push([x, y]);
      cmd = rel ? "l" : "L"; // subsequent implicit pairs are lineto
    } else if (C === "L") {
      let nx = num();
      let ny = num();
      if (rel) {
        nx += x;
        ny += y;
      }
      x = nx;
      y = ny;
      pts.push([x, y]);
    } else if (C === "H") {
      let nx = num();
      if (rel) nx += x;
      x = nx;
      pts.push([x, y]);
    } else if (C === "V") {
      let ny = num();
      if (rel) ny += y;
      y = ny;
      pts.push([x, y]);
    } else if (C === "C") {
      num();
      num();
      num();
      num();
      let nx = num();
      let ny = num();
      if (rel) {
        nx += x;
        ny += y;
      }
      x = nx;
      y = ny;
      pts.push([x, y]);
    } else if (C === "S" || C === "Q") {
      num();
      num();
      let nx = num();
      let ny = num();
      if (rel) {
        nx += x;
        ny += y;
      }
      x = nx;
      y = ny;
      pts.push([x, y]);
    } else if (C === "T") {
      let nx = num();
      let ny = num();
      if (rel) {
        nx += x;
        ny += y;
      }
      x = nx;
      y = ny;
      pts.push([x, y]);
    } else if (C === "A") {
      num();
      num();
      num();
      num();
      num();
      let nx = num();
      let ny = num();
      if (rel) {
        nx += x;
        ny += y;
      }
      x = nx;
      y = ny;
      pts.push([x, y]);
    } else if (C === "Z") {
      x = startX;
      y = startY;
    } else {
      i++; // unknown token — skip defensively
    }
  }
  return pts;
}

/** Polygon area centroid; falls back to the vertex average for tiny areas. */
function centroid(pts) {
  let A = 0;
  let cx = 0;
  let cy = 0;
  for (let k = 0; k < pts.length; k++) {
    const [x0, y0] = pts[k];
    const [x1, y1] = pts[(k + 1) % pts.length];
    const cross = x0 * y1 - x1 * y0;
    A += cross;
    cx += (x0 + x1) * cross;
    cy += (y0 + y1) * cross;
  }
  A *= 0.5;
  if (Math.abs(A) < 1e-6) {
    const n = pts.length || 1;
    const sx = pts.reduce((s, p) => s + p[0], 0) / n;
    const sy = pts.reduce((s, p) => s + p[1], 0) / n;
    return { x: sx, y: sy };
  }
  return { x: cx / (6 * A), y: cy / (6 * A) };
}

const rows = data.locations
  .filter((loc) => loc.id.toLowerCase() !== "dc")
  .map((loc) => {
    const c = centroid(absolutePoints(loc.path));
    return {
      code: loc.id.toUpperCase(),
      d: loc.path,
      label: { x: Number(c.x.toFixed(1)), y: Number(c.y.toFixed(1)) },
    };
  })
  .sort((a, b) => a.code.localeCompare(b.code));

if (rows.length !== 50) {
  console.error(`Expected 50 states, got ${rows.length}`);
  process.exit(1);
}
for (const r of rows) {
  if (!Number.isFinite(r.label.x) || !Number.isFinite(r.label.y)) {
    console.error(`Non-finite label for ${r.code}`);
    process.exit(1);
  }
}

const ts = `// AUTO-GENERATED by scripts/build-us-map.mjs — do not edit by hand.
// Source: @svg-maps/usa (MIT). DC excluded; ids upper-cased to postal codes.
export interface StatePath {
  code: string;
  d: string;
  label: { x: number; y: number };
}

export const US_VIEWBOX = ${JSON.stringify(data.viewBox)};

export const US_PATHS: StatePath[] = ${JSON.stringify(rows, null, 2)};
`;
writeFileSync(OUT, ts);
console.log(`wrote ${rows.length} states to ${OUT.pathname}`);
